id: P001712
initial_creation_type: ocr
source_metadata:
  id: bdr:W27372
  title: ཀྱེ་རྡོ་རྗེའི་མངོན་པར་རྟོགས་པ་འབྲིང་དུ་བྱ་བ་ཡན་ལག་དྲུག་པའི་མཛེས་རྒྱན
  author: ''
  volumes:
    758595459b9c4f6498bd1f3953266b0c:
      image_group_id: I1CZ958
      title: ''
      volume_number: 1
      total_pages: 154
      base_file: v001.txt
